### PR TITLE
Update to version 2.1.0

### PR DESCRIPTION
**Pull request by awvwgk**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by nicolasbock — COMMENTED** [review]
The change looks good, but CI is failing at https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=392131&view=logs&j=a05709b0-6e1e-5c64-5539-5c40db2d601d&t=6ff35a76-4d65-58c6-d0bb-61c2b88d027d&l=486 .

**Comment by awvwgk** [comment]
The build script apparently fails to actually build the library, apparently it tries to install the targets after the configuration step without actually building first. Maybe there was a change in the behaviour of the build script which we have to account for here?

**Comment by nicolasbock** [comment]
It looks like that we fixed this in https://github.com/lanl/bml/pull/526 and released `v.2.1.1` to include this fix.

**Comment by nicolasbock** [comment]
You could try this and simply bump your release to `v2.1.1`.

**Review by nicolasbock — APPROVED** [review]
:+1:

**Comment by nicolasbock** [comment]
CI is failing at https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=392171&view=logs&j=a05709b0-6e1e-5c64-5539-5c40db2d601d&t=6ff35a76-4d65-58c6-d0bb-61c2b88d027d&l=1692 now. I am not sure how to interpret this error. Does that mean that the `pkg-config` step failed?

**Comment by awvwgk** [comment]
Exactly, the version exported by CMake does not match the version that is actually packaged. At the bml repo the CMakeLists.txt still declares 2.1.0.

**Comment by nicolasbock** [comment]
Oops 😞 Let me fix.

**Comment by nicolasbock** [comment]
I released `v2.1.2`. Could you give that a try?

**Pull request merged**
